image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - name: connect
    command: |
      echo $DBT_SNOWFLAKE_PRIVATE_KEY > $GITPOD_REPO_ROOT/profiles/private_key.p8
      dbt debug
      dbt deps
    openMode: split-left
  - name: generate docs
    command: |
      dbt docs generate
      dbt docs serve --no-browser --port 8080
    openMode: split-right

vscode:
  extensions:
    - ms-python.python
    - mechatroner.rainbow-csv
    - innoverio.vscode-dbt-power-user
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - samuelcolvin.jinjahtml

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: false
