image:
  file: .gitpod.Dockerfile

tasks:
  - name: dbt
    command: |
      echo $DBT_SNOWFLAKE_PRIVATE_KEY > $GITPOD_REPO_ROOT/profiles/private_key.txt
      dbt debug
      dbt deps
vscode:
  extensions:
    - ms-python.python
    - mechatroner.rainbow-csv
    - innoverio.vscode-dbt-power-user
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - samuelcolvin.jinjahtml

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: false