default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"

      # Keypair config
      private_key_path: "{{ env_var('GITPOD_REPO_ROOT') }}/profiles/private_key.txt"

      database: "{{ env_var('DBT_SNOWFLAKE_DB') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_WH') }}"
      schema: "{{ env_var('DBT_SNOWFLAKE_SCHEMA') }}"
